name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-17
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Definir versão
        id: set_version
        run: |
          SHORT_SHA=${GITHUB_SHA::8}  # pega os 8 primeiros caracteres do SHA
          VERSION="1.0.${GITHUB_RUN_NUMBER}-${SHORT_SHA}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Versão definida: $VERSION"

      - name: Atualizar versão Maven
        run: mvn versions:set -DnewVersion=$VERSION

      - name: Build Maven
        run: mvn clean package -DskipTests

      - name: Salvar artefato
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      VERSION: ${{ needs.build.outputs.version }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Baixar artefato JAR
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: target

      - name: Login Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e push Docker
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "ERRO: JAR não encontrado!"
            exit 1
          fi

          IMAGE_TAG="${{ secrets.DOCKER_IMAGE_NAME }}:$VERSION"

          docker build --build-arg JAR_FILE="$JAR_FILE" -t "$IMAGE_TAG" .
          docker push "$IMAGE_TAG"

          docker tag "$IMAGE_TAG" "${{ secrets.DOCKER_IMAGE_NAME }}:latest"
          docker push "${{ secrets.DOCKER_IMAGE_NAME }}:latest"
